apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-11-23T01:16:45Z"
  generation: 1
  labels:
    app: feedbackapi-dep
  name: feedbackapi-dep
  namespace: default
  resourceVersion: "11779"
  uid: 5c6cc44c-ad98-40dc-bcdf-173e2cd50de7
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: feedbackapi-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: feedbackapi-dep
    spec:
      containers:
      - image: traore779/feedbackapi:v1
        imagePullPolicy: IfNotPresent
        name: feedbackapi
        livenessProbe:
          httpGet:
            path: /feedback
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 60
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-11-23T01:16:45Z"
    lastUpdateTime: "2022-11-23T01:16:45Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-11-23T01:16:45Z"
    lastUpdateTime: "2022-11-23T01:19:55Z"
    message: ReplicaSet "feedbackapi-dep-9cbd89678" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
