apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-11-23T01:06:32Z"
  generation: 1
  labels:
    app: logicapi-dep
  name: logicapi-dep
  namespace: default
  resourceVersion: "10377"
  uid: a305316b-b1d8-495a-9942-afccef3f12e3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logicapi-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logicapi-dep
    spec:
      containers:
      - image: traore779/logicapi:v1
        imagePullPolicy: IfNotPresent
        name: logicapi
        livenessProbe:
          exec:
            command: # A revoir
              - curl
              - -X POST
              - /polarity
          initialDelaySeconds: 5
          periodSeconds: 60
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-11-23T01:06:55Z"
    lastUpdateTime: "2022-11-23T01:06:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-11-23T01:06:32Z"
    lastUpdateTime: "2022-11-23T01:06:55Z"
    message: ReplicaSet "logicapi-dep-655999d69" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
